openapi: "3.0.2"
info:
  title: API FLASH HOME
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /building:
    post:
      tags:
        - Building
      summary: create Building
      description: create Building
      operationId: createNewBuilding
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildingDTO'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
components:
  schemas:
    DemoDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    BuildingDTO:
      type: object
      properties:
        name:
          type: string
          format: uuid
        description:
          type: string
        storey:
          $ref: '#/components/schemas/StoreyBuildingDTO'
        address:
          $ref: '#/components/schemas/AddressDTO'
        amenities:
          type: array
          items:
            $ref: '#/components/schemas/AmenitiesDTO'
        modality:
          $ref: '#/components/schemas/modalityDTO'
    StoreyBuildingDTO:
      enum:
        - SINGLE
        - MULTI
    AmenitiesDTO:
      type: object
      properties:
        name:
          type: string
          description: the name of the amenities of the building
        description:
          type: string
          description: the description of the amenities building
        type:
          $ref: '#/components/schemas/AmenityTypeDTO'
    AddressDTO:
      type: object
      properties:
        country:
          type: string
        cityName:
          type: string
        reference:
          $ref: '#/components/schemas/AmenityTypeDTO'
        district:
          type: string
    ReferenceDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    AmenityTypeDTO:
      enum:
        - EXTERNAL
        - INTERNAL
    modalityDTO:
      type: object
      properties:
        price:
          $ref: '#/components/schemas/MoneyDTO'
        paymentFrequency:
          $ref: '#/components/schemas/PaymentFrequencyDTO'
        caution:
          type: integer
        minimum:
          type: integer
    MoneyDTO:
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
    PaymentFrequencyDTO:
      enum:
        - MONTH
        - YEAR
